### ISSUE TITLE
Errors in config file can cause the logger to die and report no errors, stopping the process with no output

### ISSUE THREAD

**Issue by Tatsujinichi** [mage/mage#205]
For example, if you use this as your config, the empty 'server:' 
and then run 'npm run archivist:create'
mage will close with no errors
'''
logging:
    # Logging in the browser
    html5:
        # Log to the browser console
        console:
            channels:
                - ">=error"

        # Send log messages back to the server (usually errors and up)
        server:
            channels:
                - ">=error"

    server:
        # You should add logging services such as Graylog or Syslog here
'''

**Comment by stelcheck** [comment]
The reasons no logs seems to come out is that this config turns `logging.server` into a null value, which seems to somehow override the content of `config/default.yaml`.

@ronkorving how should we proceed about this one?

**Comment by stelcheck** [comment]
Second part of the issue: does it even make sense to be able to completely disable logging?

**Comment by stelcheck** [comment]
A null config ends up producing the following uncaught error right now:

```plaintext
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /home/stelcheck/Sources/mage/lib/loggingService/index.js:183:25
    at /home/stelcheck/Sources/mage/lib/loggingService/Distributor.js:44:4
    at done (/home/stelcheck/Sources/mage/node_modules/async/lib/async.js:135:19)
    at Immediate._onImmediate (/home/stelcheck/Sources/mage/node_modules/async/lib/async.js:32:16)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

Since uncaught errors are logged with... the logger, this just hard crashes, silently.

**Comment by ronkorving** [comment]
We should probably not allow no-logging-whatsoever. Perhaps we can print a warning, and turn on terminal logging that defaults to `>=error` or something?

**Comment by stelcheck** [comment]
In this case I see three "bugs":

  1. Behavior of merging objects with non-objects in Matroshyka (in this case, null)
  2. Default logger config is undefined
  3. Production configuration in template (when bootstrapping a project)

As a default, i'd log >=info personally. But we have those other questions to solve as well.
